;;; casual-suite-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from casual-suite.el

(register-definition-prefixes "casual-suite" '("casual-suite-about"))


;;; Generated autoloads from casual-suite-version.el

(register-definition-prefixes "casual-suite-version" '("casual-suite-version"))

;;; End of scraped data

(provide 'casual-suite-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; casual-suite-autoloads.el ends here
