;;; org-upcoming-modeline-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from org-upcoming-modeline.el

(put 'org-upcoming-modeline-string 'risky-local-variable t)
(defvar org-upcoming-modeline-mode nil "\
Non-nil if Org-Upcoming-Modeline mode is enabled.
See the `org-upcoming-modeline-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `org-upcoming-modeline-mode'.")
(custom-autoload 'org-upcoming-modeline-mode "org-upcoming-modeline" nil)
(autoload 'org-upcoming-modeline-mode "org-upcoming-modeline" "\
Show next upcoming `org-mode' event in mode line.

This is a global minor mode.  If called interactively, toggle the
`Org-Upcoming-Modeline mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='org-upcoming-modeline-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "org-upcoming-modeline" '("org-upcoming-modeline-"))

;;; End of scraped data

(provide 'org-upcoming-modeline-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; org-upcoming-modeline-autoloads.el ends here
